# Generated by Django 4.2.5 on 2023-09-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('image', models.ImageField(null=True, upload_to='blogs/%Y/%m/%d/')),
                ('author', models.CharField(max_length=50)),
                ('data_posted', models.DateTimeField(auto_now_add=True)),
                ('data_modified', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('DevOps', 'DevOps'), ('General', 'General'), ('Networking', 'Networking')], default='General', max_length=100)),
                ('text', models.TextField()),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
