# Generated by Django 4.2.5 on 2023-09-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Networking', 'Networking'), ('General', 'General'), ('DevOps', 'DevOps')], default='General', max_length=100),
        ),
    ]
