# Generated by Django 4.2.5 on 2023-09-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('DevOps', 'DevOps'), ('Networking', 'Networking'), ('General', 'General')], default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='blogs/static/blogs/%Y/%m/%d/'),
        ),
    ]
