# Generated by Django 4.2.5 on 2023-09-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_category_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='fhqxobditl'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('DevOps', 'DevOps'), ('General', 'General'), ('Networking', 'Networking')], default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='blogs/static/blogs/'),
        ),
    ]
